workflow ANNOTATE_PROTEIN_CODING_GENES {
    take:
        masked_genomes

    main:
    MAKER_BY_SIMILARITY(masked_genomes)

    FILTER_MAKER_PREDICTIONS(MAKER_BY_SIMILARITY.out)

    HMM_WITH_AUGUSTUS_1(FILTER_MAKER_PREDICTIONS.out)
    HMM_WITH_SNAP_1(MAKER_BY_SIMILARITY.out)

    MAKER_AB_INITIO_1(HMM_WITH_AUGUSTUS_1.out, HMM_WITH_SNAP_1.out)

    HMM_WITH_AUGUSTUS_2(MAKER_BY_SIMILARITY.out)
    HMM_WITH_SNAP_2(MAKER_BY_SIMILARITY.out)

    MAKER_AB_INITIO_2(HMM_WITH_AUGUSTUS_2.out, HMM_WITH_SNAP_2.out)


    emit:
        annotated_genomes
}
